<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

 /** @var \Magento\Newsletter\Block\Subscribe $this */
?>
<div class="block newsletter">
    <?php /* <div class="title"><strong><?= $block->escapeHtml(__('Newsletter')) ?></strong></div>  */ ?>
    <div class="content">
        <span class="label">
            <div class="label__wrapper">
                <span>
                    Cadastre-se para receber
                </span>
                <strong>Novidades</strong>
            </div>
        </span>
        <form class="form subscribe" novalidate action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>" method="post" data-mage-init='{"validation": {"errorClass": "mage-error"}}' id="newsletter-validate-detail">
            <div class="field newsletter">
                <label for="newsletter">
                    <input name="name" type="text" id="newsletter-name" placeholder="<?= $block->escapeHtml(__('Enter your name')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true}" />
                    <input name="email" type="email" id="newsletter-email" placeholder="<?= $block->escapeHtml(__('Enter your email address')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}" />
                    <div class="actions">
                        <button class="action subscribe primary" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" type="submit" aria-label="Subscribe">
                            <span><?= $block->escapeHtml(__('Subscribe')) ?></span>
                        </button>
                    </div>
                </label>
            </div>
        </form>
    </div>
</div>
